flant/shell-operator

- cmd/shell-operator/main.go
- pkg/app/app.go
- pkg/shell-operator/operator.go
The issue has arisen, when I had to run multiple shell-operator images in a single pod.
> Add an option to specify listening address for HTTP server

- HOOKS.md
- pkg/hook/kube_event/hooks_controller.go
- pkg/hook/kube_event/kube_event_hook.go
- pkg/kube_events_manager/kube_event.go
- pkg/kube_events_manager/kube_events_manager.go
1. There are some object that lack labels. For example: Service and corresponding Endpoint `kubernetes` in `default` Namespace. I may have an interest in this exact object (whose name is the same across all Kubernetes clusters on planet Earth), but I don't want to muck around with labelings.
2. If I were to use [resourceNames](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#policyrule-v1-rbac-authorization-k8s-io) field in Role or ClusterRole, I'd find that client-go's Reflector component would fail with an error:
```
E0628 13:53:29.852940       1 reflector.go:125] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:350: Failed to list *unstructured.Unstructured: endpoints is forbidden: User "system:serviceaccount:kube-system:node-local-dns" …
```
> Allow subscribing to Kubernetes events by concrete object name

- HOOKS.md
Old link shows us a new version of package documentation, but you use v2 version, not v3. It can mislead readers.
> CHANGE link to cron package documentation

- pkg/hook/hooks_queue.go
- pkg/hook/kube_event/hooks_controller.go
- pkg/kube_events_manager/kube_events_manager.go
- pkg/kube_events_manager/kube_events_manager_test.go
- pkg/kube_events_manager/monitor.go
- pkg/kube_events_manager/namespace_informer.go
- pkg/kube_events_manager/resource_informer.go
- pkg/shell-operator/operator.go
- pkg/task/task.go
Run hooks with Synchronization event for kubernetes binding right after hooks with onStartup binding.  Note: `v1` feature.
> fix: Run kubernetes hooks with Synchronization event after onStartup

- .github/workflows/main.yaml
- Dockerfile
- Dockerfile-alpine3.9
- cmd/shell-operator/main.go
- go.mod
- go.sum
- pkg/app/app.go
- pkg/kube_events_manager/resource_informer.go
- pkg/kube_events_manager/util.go
- pkg/shell-operator/operator.go
This PR enables use of `jq` as a library with https://github.com/flant/libjq-go to speed up `jqFilter` execution. The dark side is that `shell-operator` should be built with CGO_ENABLED=1 now.
> feat: libjq-go to cache compiled jq filters

- test/hook/context/README.md
- test/hook/context/generator.go
- test/hook/context/generator_test.go
The PR adds the ability to generate binding contexts for schedules. 
After adding includeSnapshotsFrom option to schedule config we need to generate binding contexts for it too to cover hooks, that take Kubernetes cluster state periodically.
> feat: generate binding contexts for schedule bindings

- go.mod
- go.sum
jq downgraded to tag jq-1.6. More info in issue: https://github.com/flant/libjq-go/issues/6
> fix: jq crashes on try+fromjson expressions

- pkg/kube/fake/resources.go
There are some rare resources in non preferred API version groups, like CSINode in storage/v1beta1.
This PR adds missed resources to the fake cluster.
> Add kubernetes resources from non preferred API versions

- pkg/kube/client.go
KubeClient.GroupVersionResource regression — result gvr with an empty group and version when apiVersion is empty (search by kind).
> fix: group and version for gvr by kind only

- pkg/kube/client.go
https://github.com/kubernetes/client-go/issues/564
> feat: expose settings for RateLimiter in kubernetes client

- frameworks/shell/hook.sh
To avoid problems with a shared variable namespace in hooks we decided to run every hook handler as a subprocess.
> shell-framework: run hooks as subprocesses

- pkg/hook/controller/schedule_bindings_controller.go
- pkg/shell-operator/operator.go
- pkg/task/task.go
Example queue dump from addon-operator:
```
DiscoverModulesState:main:::PrepopulateMainQueue:failures 3:module hook --config run problem
```
> feat: fail description and count for failed tasks in queue dump

- HOOKS.md
- METRICS.md
- README.md
- RUNNING.md
- examples/001-startup-shell/README.md
TODO: 
~- [ ] Replace every JSON example with YAML~
There should be a way to properly present available syntax options without resorting to EBNF notation or mocking a JSON document...
> Documentation proofreading

- pkg/hook/binding_context/binding_context.go
- pkg/hook/binding_context/binding_context_test.go
- pkg/hook/config/schemas.go
- pkg/hook/controller/hook_controller.go
- pkg/hook/controller/kubernetes_bindings_controller.go
- pkg/hook/controller/schedule_bindings_controller.go
- pkg/hook/hook_config.go
- pkg/hook/hook_config_test.go
- pkg/hook/task_metadata/task_metadata.go
- pkg/hook/task_metadata/task_metadata_test.go
- pkg/hook/types/bindings.go
- pkg/shell-operator/operator.go
- pkg/shell-operator/operator_test.go
- pkg/task/dump/dump.go
- pkg/task/dump/dump_test.go
- pkg/task/queue/task_queue.go
- group key clears all sibling tasks with similar key
- fix panic when queue is not created yet
- fix task description in queue dump: show binding, group, hook name
- show queue status in dump: run/sleep after fail/waiting seconds
_fixes #149 _
> feat: group key to combine tasks in queue into one binding context

- HOOKS.md
- pkg/hook/binding_context/binding_context.go
- pkg/hook/binding_context/binding_context_test.go
- pkg/hook/hook_config_test.go
- pkg/shell-operator/operator.go
- pkg/shell-operator/operator_test.go
A `type` field for group can be `Synchronization` if at most one binding context in a group had `Synchronization` type. If grouped contexts do not have `Synchronization` context, then the type is `Group`.
A binding context for Schedule now has field type with value `Schedule`.
Fixes #156.
> feat: add type field for group and schedule

- HOOKS.md
- pkg/hook/config/schemas.go
- pkg/hook/config/validator_test.go
- pkg/hook/controller/kubernetes_bindings_controller.go
- pkg/hook/hook_config.go
- pkg/hook/hook_config_test.go
- pkg/hook/types/bindings.go
- pkg/shell-operator/operator.go
To define a binding that only needed to catch a snapshot and do not require a hook execution:
```yaml
configVersion: v1
kubernetes:
- name: pods-snapshot
kind: Pod
executeHookOnEvent: []
executeHookOnSynchronization: false
schedule:
- name: every_1_min
crontab: "* * * * *"
includeSnapshotsFrom: ["pods-snapshots"]
```
A hook with this configuration will be executed every 1 minute with pods. And will _not_ be executed on kubernetes event or after onStartup.
> feat: executeHookOnSynchronization for kubernetes binding

- METRICS.md
- go.sum
- pkg/hook/hook.go
- pkg/metrics_storage/metric_operation.go
- pkg/metrics_storage/metrics_storage.go
- pkg/shell-operator/operator.go
Use METRICS_PATH file to send operations in JSON format.
Operation add a counter:
{"name":"metric_name","add":1,"labels":{"label1":"value1"}}
Operation to set a gauge value:
{"name":"metric_name","set":33,"labels":{"label1":"value1"}}
labels are optional.
> feat: allow to send metrics from hooks

- test/hook/context/generator.go
- test/hook/context/generator_test.go
Group compaction works on the task level for the shell-operator main workflow. This PR adds the behavior of group compaction for binding context generator because the context generator knows nothing about tasks. This PR also provides the unit test.
> fix: add group compaction to binding context generator

- README.md
Remove stray `"` from the README example to avoid the following error:
> MAIN Fatal: initialize hook manager: creating hook 'pods-hook.sh': load hook 'pods-hook.sh' config: 1 error occurred:\n\t* .kubernetes\" is a forbidden property\n\n\nhook --config output: configVersion: v1\nkubernetes\":\n- apiVersion: v1\n  kind: Pod\n  executeHookOnEvent: [\"Added\"]\n\n
> Fix example pods-hook.sh YAML

- cmd/shell-operator/main.go
- pkg/executor/zombie_reaper.go
- pkg/hook/config/schemas.go
- pkg/hook/controller/hook_controller.go
- pkg/hook/controller/kubernetes_bindings_controller.go
- pkg/hook/hook_config.go
- pkg/hook/types/bindings.go
- pkg/shell-operator/operator.go
- pkg/shell-operator/operator_test.go
- pkg/task/queue/queue_set.go
- pkg/task/queue/task_queue.go
- repeat action and Remove method for task queue
- custom combine condition for CombineBindingContext
- WaitForSynchronization field in kubernetes binding
- zombie reaper is locked by default
> feat: repeat action for tasks for implementing 'wait' behaviour

- HOOKS.md
- README.md
- go.sum
- pkg/hook/config/schemas.go
- pkg/hook/hook_config.go
- pkg/hook/types/bindings.go
- pkg/kube_events_manager/monitor_config.go
- pkg/kube_events_manager/resource_informer.go
- pkg/kube_events_manager/types/types.go
- pkg/kube_events_manager/util.go
- keepFullObjectsInMemory can be used to keep only filterResult for binding context.
- changes and improvements in documentation.
- new metrics to monitor snapshots: cached objects count and size in bytes.
> feat: new property to remove full objects from snapshot

- pkg/app/app.go
- pkg/hook/hook_manager.go
- pkg/metric_storage/metric_storage.go
- pkg/metric_storage/vault/vault.go
- pkg/metric_storage/vault/vault_test.go
- pkg/shell-operator/operator.go
- hook-metrics-listen-port flag to specify a listen port for hook metrics
- fix labels cardinality for kube_event_manager metrics
> feat: separate port for hook metrics

- test/hook/context/generator.go
- test/hook/context/generator_test.go
In the case of long-running tests, the user may need to adjust timeouts.
> feat: Add ability to change timeouts in binding context generator

- .github/workflows/build.yaml
- .github/workflows/dev-build.yaml
- .github/workflows/lint.yaml
- .github/workflows/release-build.yaml
- .github/workflows/tests.yaml
- cmd/shell-operator/main.go
- pkg/task/queue/task_queue.go
- pkg/utils/exponential_backoff/delay.go
- pkg/utils/exponential_backoff/delay_test.go
Increase delay exponentially on each retry from 5s to 32s.
./logs.sh | jq '.time + " " + .msg ' | grep retry
"2020-11-18T09:21:41Z Hook failed. Will retry after delay. Failed count is 1. Error: with-error.sh FAILED: exit status 1"
"2020-11-18T09:21:46Z Hook failed. Will retry after delay. Failed count is 2. Error: with-error.sh FAILED: exit status 1"
"2020-11-18T09:21:53Z Hook failed. Will retry after delay. Failed count is 3. Error: with-error.sh FAILED: exit status 1"
"2020-11-18T09:22:01Z Hook failed. Will retry after delay. Failed count is 4. Error: with-error.sh FAILED: exit status 1"
"2020-11-18T09:22:10Z Hook failed. Will retry after delay. Failed count is 5. Error: with-error.sh FAILED: exit status 1"
"2020-11-18T09:22:24Z Hook failed. Will retry after delay. Failed count is 6. …
> feat: exponential backoff for hook retries

- pkg/utils/exponential_backoff/delay.go
- pkg/utils/exponential_backoff/delay_test.go
> fix: prevent overflow in exponential backoff calculation

- go.mod
- pkg/jq/cgo_filter.go
- pkg/jq/exec_filter.go
- pkg/jq/filter.go
- pkg/jq/nocgo_filter.go
- pkg/kube_events_manager/filter.go
- pkg/kube_events_manager/resource_informer.go
- pkg/kube_events_manager/util.go
flant/libjq-go is required only if cgo is enabled.
Build with CGO_ENABLED=0 is not require libjq-go anymore, so it is possible to use various parts of the shell-operator in projects that don't require jqFilter. For example, Kubernetes client in `pkg/kube` or Prometheus client in `pkg/metric_storage` or Monitors with custom FilterFunc in `pkg/kube_events_manager`.
`JQ_EXEC=yes` environment variable still can be used to force `/usr/bin/jq` execution if the shell-operator is built with cgo enabled.
```release-note
NONE
```
> feat: no cgo build

- HOOKS.md
* Remove fullObjectInSnapshot mentions from HOOKS.md
Closes #240
No, it doesn't.
> fix: remove fullObjectInSnapshot from docs

- test/hook/context/generator.go
Call UpdateSnapshots in `generator.go` to get snapshots in hook tests.
`HookCtrl.HandleKubeEvent` method does not return snapshots anymore to use less memory for queued tasks.
```release-note
```
> fix: add UpdateSnapshots in generator.go

- examples/204-validating-webhook/Dockerfile
Do not add files from context that are already present in base image `flant/shell-operator:latest`.
Currently the build fails with:
```
Step 3/5 : ADD frameworks/shell /frameworks/shell
ADD failed: file not found in build context or excluded by .dockerignore: stat frameworks/shell: file does not exist
```
No.
> frameworks and shell-operator already in base image

- pkg/hook/hook_manager.go
Capture and propagate stderr for hook --config
Closes #221
> fix: log stderr for hook --config

- HOOKS.md
- examples/220-execution-rate/.dockerignore
- examples/220-execution-rate/.helmignore
- examples/220-execution-rate/Chart.yaml
- examples/220-execution-rate/Dockerfile
- examples/220-execution-rate/README.md
- examples/220-execution-rate/crontab-recreate.sh
- examples/220-execution-rate/hooks/settings-rate-limit.sh
- examples/220-execution-rate/templates/crd/crontab.yaml
- examples/220-execution-rate/templates/deployment.yaml
- examples/220-execution-rate/templates/rbac.yaml
- examples/220-execution-rate/values.yaml
- go.mod
- pkg/hook/config/config.go
- pkg/hook/config/config_test.go
- pkg/hook/config/config_v1.go
- pkg/hook/config/schemas.go
- pkg/hook/hook.go
- pkg/hook/types/bindings.go
- pkg/shell-operator/operator.go
- pkg/task/queue/task_queue.go
Introduce settings to set execution rate for a hook.
Shell-operator can combine tasks in the queue and run the hook once with an array of binding contexts. Execution rate settings help to handle multiple events that are occurred during a short period.
Yes, the new section "settings" is added to the configuration.
```release-note
```
> feat: execution rate settings for hook

- KUBERNETES.md
- go.mod
- pkg/hook/binding_context/binding_context.go
- pkg/hook/binding_context/binding_context_test.go
- pkg/hook/hook.go
- pkg/kube/object_patch/patch.go
- pkg/kube/object_patch/patch_test.go
- pkg/kube/object_patch/testdata/serialized_operations/invalid_create.yaml
- pkg/kube/object_patch/testdata/serialized_operations/invalid_delete.yaml
- pkg/kube/object_patch/testdata/serialized_operations/invalid_patch.yaml
- pkg/kube/object_patch/testdata/serialized_operations/valid_create.yaml
- pkg/kube/object_patch/testdata/serialized_operations/valid_delete.yaml
- pkg/kube/object_patch/testdata/serialized_operations/valid_patch.yaml
- pkg/kube/object_patch/types.go
- pkg/kube/object_patch/validation.go
- pkg/kube/object_patch/validation_test.go
- pkg/shell-operator/operator.go
- pkg/shell-operator/operator_test.go
- test/integration/kubeclient/object_patch_test.go
- test/integration/suite/run.go
- test/utils/kind-k8s-cluster.go
Provide a way to delegate Kubernetes object manipulation to the shell-operator. Will remove the need to use kubectl.
```release-note
```
> Object manipulation framework

- RUNNING.md
- pkg/app/kube-client.go
- pkg/kube/client.go
- pkg/kube/metrics.go
- pkg/shell-operator/kube_client.go
- pkg/shell-operator/operator.go
Custom labels for metrics exported by the kube client.
It is needed to distinguish metrics when multiply clients are in use. addon-operator needs this.
```release-note
```
> feat: custom metrics for kube client

- .github/workflows/build.yaml
- .github/workflows/tests.yaml
- HOOKS.md
- pkg/hook/binding_context/binding_context.go
- pkg/hook/controller/hook_controller.go
- pkg/hook/controller/kubernetes_bindings_controller.go
- pkg/hook/task_metadata/task_metadata.go
- pkg/kube_events_manager/kube_events_manager.go
- pkg/kube_events_manager/kube_events_manager_test.go
- pkg/kube_events_manager/monitor.go
- pkg/kube_events_manager/resource_informer.go
- pkg/shell-operator/operator.go
- pkg/shell-operator/operator_test.go
- pkg/task/queue/task_queue.go
- test/hook/context/generator.go
- test/integration/kube_event_manager/kube_event_manager_test.go
- test/utils/kind-k8s-cluster.go
Set `objects` in "Synchronization" binding context to an actual state in cluster.
- snapshots in monitors are updated without Event tasks until success Synchronization execution
- fix documentation for "Group" binding context
Integration tests are fixed, but there are 3 clusters in use. We need to refactor this part in the future.
```release-note
```
> fix: fresh objects for Synchronization executions

- examples/210-conversion-webhook/.dockerignore
- pkg/webhook/conversion/crd_client_config.go
- pkg/webhook/conversion/handler.go
Add v1beta1 to the `conversionReviewVersions` list.
`v1` only in conversionReviewVersion leads to an error on Kubernetes 1.16:
```
{"level":"error","msg":"ConversionWebhookManager Start: CustomResourceDefinition.apiextensions.k8s.io \"crontabs.stable.example.com\" is invalid: spec.conversion.conversionReviewVersions: Invalid value: []string{\"v1\"}: must include at least one of v1beta1","time":"2021-05-04T11:17:45Z"}
```
Despite the alert "Conversion webhooks must respond with a ConversionReview object in the same apiVersion they receive.", Shell-operator returns v1.ConversionReview and it works well on 1.16+. Also, input ConversionReview is always v1 for 1.16+. So, just adding  "v1beta1" to the list is enough. 
```release-note
```
> fix: add v1beta1 to conversion config to work with 1.16+

- pkg/kube/fake/scripts/resources_generator
- pkg/kube/fake/v116_resources.go
- pkg/kube/fake/v117_resources.go
- pkg/kube/fake/v118_resources.go
- pkg/kube/fake/v119_resources.go
- pkg/kube/fake/v120_resources.go
- pkg/kube/fake/v121_resources.go
Generated all resources for k8s fake cluster from 1.16 to 1.21 
Previously we had only preferred versions generated. It affects some clusters like 1.16
This PR has all resources generated
NONE
> Generate full resources not only preferred

- .gitignore
- METRICS.md
- pkg/kube/metrics.go
- pkg/kube_events_manager/resource_informer.go
- pkg/metric_storage/metric_storage.go
- pkg/metric_storage/operation/operation.go
- pkg/metric_storage/vault/vault.go
- pkg/shell-operator/metrics.go
- pkg/shell-operator/operator.go
- pkg/task/queue/task_queue.go
These changes add support for using the observe action on custom metrics from hooks
For custom metrics, we have the "add", "set" (and "expire") actions available in the hook, which correspond to counters and gauges respectively. In order to observe a duration from inside the hook into a custom metric, this PR adds support for the "observe" action. This is useful for wanting to observe durations for different parts of the hook's code.
Additionally, there are a few unrelated minor changes (increasing durations of buckets to cover usecases of longer-running hooks for "core" metrics), .gitignore and a couple of typos
```release-note
Add support for observing a histogram duration in custom, non-grouped metrics
```
> Add histogram support for custom (non-grouped) metrics

- pkg/kube/object_patch/patch.go
- pkg/kube/object_patch/patch_collector.go
- pkg/kube/object_patch/spec_generator.go
- pkg/kube/object_patch/types.go
- pkg/metric_storage/metric_storage.go
- pkg/metric_storage/operation/operation.go
Add SpecGenerator to create SpecOperations for ObjectPatcher instead on instantly executing
Used to collect spec in go-hooks and then execute them at once
after hook has been completed. We need it for making the same behavior for shell-hooks and go-hooks 
NONE
```release-note
```
> Add SpecGenerator which is compatible with ObjectPatcher

- pkg/kube/object_patch/patch.go
- test/utils/shell-operator.go
Fix logic behind `*IfExists` options of Create operation.
Return non 'already exists' error from a `Create` call if `ignoreIfExists` or `updateIfExists` is set.
```release-note
```
> fix: always return non 'already exists' error for Create operation

- BINDING_VALIDATING.md
- pkg/webhook/validating/handler.go
- pkg/webhook/validating/types/response.go
- pkg/webhook/validating/types/response_test.go
- pkg/webhook/validating/types/testdata/response/good_allow_warnings.json
Added ability to send warnings as result of validating webhooks.
Starting in v1.19, admission webhooks can optionally return warning messages.
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#response
```release-note
```
> Added warnings in validation webhooks

- Dockerfile
bump kubectl version from 1.19.11 to 1.21.8
> bump kubectl version from 1.19.11 to 1.21.8

- pkg/app/log.go
- fix logrus output timestamp format (full timestamp)
LOG_TYPE=color now prints full time.
Before:
After:
> enable FullTimestamp output for logrus color mode

- cmd/shell-operator/main.go
- pkg/app/log.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/debug/client.go
- pkg/debug/debug-cmd.go
- pkg/debug/server.go
- pkg/shell-operator/operator.go
- test/integration/kube_event_manager/kube_event_manager_test.go
- Add runtime configuration parameter "log.level".
- Add a `config` command to list and set runtime parameters.
- A runtime parameter can be set for a period of time.
Change "log.level" on the fly enable debugging without restart.
Also, config with runtime parameters is the one more step to implement https://github.com/flant/shell-operator/issues/101
```release-note
```
> feat: runtime config for "live" debugging options

- pkg/hook/hook.go
- pkg/hook/hook_test.go
Set defaults for creating rate limiter if hook execution settings is empty but not nil.
In Addon-operator now has special flag for enable schedule  go-hook before first converge.
This flag was added into [HookConfigSettings](https://github.com/flant/addon-operator/pull/300/files#diff-afc24ed4293764eb4427af841e54f863dabd28d1dbb9d1772423dd83d8c5a69cR162) 
If this struct is not nil, its fields will be copied into Shell-operator hook Settings struct. Depend on this struct shell operator create rate limiter and if this settings struct is nil create rate limiter with defaults. We need to check that empty values in settings  (when struct was created but fields was not filled) will create rate limiter with default settings and if need - fix it.
```release-note
```
> Set defaults for creating rate limiter if hook execution settings is empty but not nil.

- Dockerfile
- kubectl 1.21.8 built with vulnerable Go 1.16.12
- Use kubectl 1.21.10 built with Go 1.16.14.
- Update alpine to 3.15.
```
Binaries from v1.0.8:
$  kubectl version
Client Version: version.Info{... GitVersion:"v1.21.8", ... GoVersion:"go1.16.12" ...}
$  go version shell-operator
shell-operator: go1.16.15
```
Fix #367
```release-note
```
> fix: update versions to address CVE-2022-23806

- Dockerfile
change the base image from alpine:3.15 to alpine:3.15.4
to fix the https://github.com/flant/shell-operator/issues/387
Scan the image with harbor . The fix is worked.
> fix: update alpine to address CVE-2022-28391

- pkg/shell-operator/bootstrap.go
- pkg/shell-operator/operator.go
Restore separate metrics storage for hooks.
No metrics from hooks when separate port for hook metrics is in use after applying #388.
```release-note
```
> fix: restore separate metric storage after #388

- pkg/task/queue/task_queue.go
- pkg/task/queue/task_queue_test.go
Restore exponential backoff for delayed between  failed hooks restarts.
Failed hook restarts every second after merging #388.
```release-note
```
> fix: restore exponential backoff after #388

- pkg/hook/controller/hook_controller.go
- pkg/hook/controller/hook_controller_test.go
- pkg/hook/controller/kubernetes_bindings_controller.go
Remove centralized cache in KubernetesBindingsController.
Move cache to HookController.UpdateSnapshots to make it
individual for each hook execution.
Fix #386 
First solution was to add Lock/Unlock on cache map, but it turns out that single map approach is a bad design.
UpdateSnapshots is called from different queues, and individual cache for each call is a better solution.
Also note, `Monitor.Snapshot()` call is synchronized.
```release-note
NONE
```
> fix: prevent map write race for cached snapshot update

- pkg/kube_events_manager/monitor.go
- pkg/kube_events_manager/monitor_test.go
Add flag to enable KubeEvents for varying informers after Synchronization phase.
See #379 and #399. This fix enables events for hooks with namespace.labelSelector.
"before" situation can be emulated by commenting `m.eventsEnabled = true` in monitor.go. Test will fail:
```
monitor_test.go:119: 
Timed out after 5.000s.
Should fire KubeEvent after Synchronization
Expected
<bool>: false
to be true
```
```release-note
```
> fix: enable kube events for hooks with namespace.labelSelector bindings

- go.mod
- go.sum
- pkg/debug/server.go
- pkg/shell-operator/debug_server.go
- pkg/utils/structured-logger/structured-logger.go
- pkg/webhook/conversion/handler.go
- pkg/webhook/server/server.go
- pkg/webhook/server/server_test.go
- pkg/webhook/validating/handler.go
Signed-off-by: Ivan Mikheykin <ivan.mikheykin@flant.com>
Update go-chi to v5.0.7.
Dependabot tries to [update](https://github.com/flant/shell-operator/pull/389) go-chi to the latest incompatible version v4.1.2, but this version changes signature for `StructuredLoggerEntry.Write` method, so PR fails.
Latest go-chi is v5.0.7 and is compatible with v4.1.2.
> fix(deps): bump github.com/go-chi/chi from 4.0.3+incompatible to 5.0.7

- pkg/kube_events_manager/factory.go
- pkg/kube_events_manager/kube_events_manager.go
- pkg/kube_events_manager/monitor.go
- pkg/kube_events_manager/namespace_informer.go
- pkg/kube_events_manager/resource_informer.go
- test/hook/context/generator.go
- test/hook/context/generator_test.go
- test/hook/context/state.go
Reuse watch and cache for informers
The most resources shell-operator consume to encode and decode watch events.
```release-note
```
> Use Factory for informers

- METRICS.md
- pkg/kube_events_manager/filter.go
- pkg/kube_events_manager/resource_informer.go
- pkg/kube_events_manager/types/types.go
- pkg/shell-operator/metrics_operator.go
Remove kube_snapshot_bytes metric and snapshot size calculations.
This metric is not reliable:
- Informers cache objects internally.
- Informers factory reduce memory footprint.
- `keepFullObjectsInMemory: false` removes object size from metric.
- Metric value not correlate with total memory consumtion, it may be 5MiB and shell-operator consume 1.5GiB.
```release-note
- Remove kube_snapshot_bytes metric.
```
> feat: remove kube_snapshot_bytes metric and size calculations

- test/hook/context/generator.go
Create new informers factory on creating BindingContextController in testing generator.
Informer is cached with fake client and tests become broken. See https://github.com/deckhouse/deckhouse-test-1/actions/runs/3206032635/jobs/5239370058
Alternative solution is to add AfterEach to all tests https://github.com/deckhouse/deckhouse/pull/1937/files. Creating new factory at start seems more logical.
```release-note
```
> fix: initialize informers factory at generator start

- pkg/shell-operator/operator.go
RunMetrics starts go routines that access the TaskQueueSet info thus data race appears at start.
```
==================
WARNING: DATA RACE
Read at 0x00c00026fbc0 by goroutine 50:
github.com/flant/shell-operator/pkg/task/queue.(*TaskQueueSet).Iterate()
github.com/flant/shell-operator/pkg/shell-operator.(*ShellOperator).RunMetrics.func2()
Previous write at 0x00c00026fbc0 by main goroutine:
runtime.mapassign_faststr()
/usr/local/Cellar/go/1.17.2/libexec/src/runtime/map_faststr.go:202 +0x0
github.com/flant/shell-operator/pkg/task/queue.(*TaskQueueSet).NewNamedQueue()
...
Goroutine 50 (running) created at:
github.com/flant/shell-operator/pkg/shell-operator.(*ShellOperator).RunMetrics()
...
```
> fix: run metrics storage after bootstraping queues

- pkg/kube_events_manager/error_handler.go
- pkg/kube_events_manager/factory.go
- pkg/kube_events_manager/resource_informer.go
- pkg/shell-operator/metrics_operator.go
Add WatchErrorHandler implementation to log informer errors and increase new metric counter.
shell-operator will log messages about problems with connection to the apiserver:
```
{"hook":"pods-v1.sh","level":"error","msg":"kubernetes[0]{crontabs}: Failed to watch ct: failed to list *unstructured.Unstructured: Get \"https://10.96.0.1:443/apis/stable.example.com/v1/crontabs?resourceVersion=369642\": dial tcp 10.96.0.1:443: connect: connection refused","time":"2022-12-13T11:59:21Z"}
```
```
shell_operator_kubernetes_client_watch_errors_total{error_type="fail"} 15
```
```release-note
```
> feat: add watch error handler for Kubernetes client

- cmd/shell-operator/main.go
- pkg/jq/apply_jq_exec.go
- pkg/jq/apply_libjq-go.go
- pkg/jq/jq_exec.go
- execute jq binary without absolute path
- 'version' command now prints jq implementation info
Absolute path makes local testing problematic.
```release-note
```
> fix: execute jq binary without absolute path

- .github/workflows/publish-dev.yaml
- .github/workflows/publish-release.yaml
- README.md
- RUNNING.md
- examples/001-startup-shell/Dockerfile
- examples/002-startup-python/Dockerfile
- examples/003-common-library/Dockerfile
- examples/101-monitor-pods/Dockerfile
- examples/102-monitor-namespaces/Dockerfile
- examples/103-schedule/Dockerfile
- examples/104-secret-copier/Dockerfile
- examples/105-crd-simple/Dockerfile
- examples/106-monitor-events/Dockerfile
- examples/200-advanced/Dockerfile
- examples/201-install-with-helm-chart/README.md
- examples/201-install-with-helm-chart/templates/shell-operator-deployment.yaml
- examples/202-repack-build/Dockerfile
- examples/204-validating-webhook/Dockerfile
- examples/206-mutating-webhook/Dockerfile
- examples/210-conversion-webhook/Dockerfile
- examples/220-execution-rate/Dockerfile
This PR is a reaction to recent Docker, Inc. actions: send [notification](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) and then [apologize](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) about free team accounts deletion. This may affect our docker hub account in the futute.
- This PR adds second image storage ghcr.io (Github Container Registry) to improve reliability.
- Release workflow still pushes latest images to dockerhub in addition to gchr.io.
- Some recent tags have been copied from https://hub.docker.com/r/flant/shell-operator to https://github.com/flant/shell-operator/pkgs/container/shell-operator/versions?filters%5Bversion_type%5D=tagged
- This PR prepend …
> feat(ci): store images in ghcr.io/flant/shell-operator

- examples/204-validating-webhook/templates/deployment.yaml
- examples/206-mutating-webhook/templates/deployment.yaml
- examples/210-conversion-webhook/templates/deployment.yaml
- pkg/webhook/admission/handler.go
- pkg/webhook/admission/handler_test.go
- pkg/webhook/conversion/handler.go
Dedicate /healthz route for admission and conversion controllers
Without this route we can do only tcpCheck which will fail on the TCP Handshake.
We want to check service liveness gracefully with extra logs
> Add healthz handler

- examples/206-mutating-webhook/hooks/mutating.sh
When you have a bigger operation to patch, base64 will return output in multiple lines.
This will cause an error:
```
Error: got bad validating response: invalid character '\\n' in string literal
```
Which is hard to diagnose. Only having base64 output in oneliner makes it work correctly.
I wasted a few hours debugging that issue and it was caused by base64. I think it will help others when they will be working on the examples.
none :)
> Adding single line output for base64

- .github/workflows/docs.yaml
We need to fix GitHub Actions warning `Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`
Update actions/checkout version from v2 to v3.
> Fix GitHub Actions warnings

- pkg/kube_events_manager/kube_events_manager.go
- pkg/task/queue/queue_set.go
- test/integration/kubeclient/kube_client_test.go
Fix a couple of race conditions:
```
WARNING: DATA RACE
Write at 0x00c000da9860 by main goroutine:
runtime.mapassign_faststr()
/usr/local/go/src/runtime/map_faststr.go:203 +0x0
github.com/flant/shell-operator/pkg/task/queue.(*TaskQueueSet).NewNamedQueue()
/go/pkg/mod/github.com/flant/shell-operator@v1.2.0/pkg/task/queue/queue_set.go:72 +0x22b
Previous read at 0x00c000da9860 by goroutine 63:
github.com/flant/shell-operator/pkg/task/queue.(*TaskQueueSet).Iterate()
/go/pkg/mod/github.com/flant/shell-operator@v1.2.0/pkg/task/queue/queue_set.go:108 +0xe8
```
----
```
WARNING: DATA RACE
Read at 0x00c000da98f0 by goroutine 935:
runtime.mapaccess2_faststr()
/usr/local/go/src/runtime/map_faststr.go:108 +0x0
github.com/flant/shell-operator/pkg/kube_events_manager.(*kubeEventsManager).HasMonitor() …
```
> chore(go): Fix race conditions

- pkg/kube_events_manager/filter.go
- pkg/kube_events_manager/filter_test.go
- test/integration/kubeclient/kube_client_test.go
Add function name to the output for FilterFunc error.
It's hard to understand, which function generated an error in the runtime, especially if we have a few hooks in a module. With this change we can easily locate problem function and fix it.
Now we have an error like:
```
"filterFn: invalid character 'a' looking for beginning of value"
```
new signature is:
```
"filterFn (github.com/flant/shell-operator/pkg/kube_events_manager.filterFuncWithError) contains an error: invalid character 'a' looking for beginning of value"
```
> Add verbosity if FilterFunction contains an error

- pkg/executor/executor.go
- pkg/executor/executor_test.go
Change stdout/stderr logger for hooks
Avoid 64Kb of a scanner. Implementing custom io.Writer can handle logs of any size
Close(https://github.com/flant/shell-operator/issues/297)
> Change hook logger

- pkg/hook/config/config_v1.go
- pkg/hook/controller/hook_controller.go
When we specify values for `includeSnapshotsFrom:` and `group:` in the `KubernetesMutating` binding, the snapshots from the other bindings referenced are not added to the binding-context of `"type": "Mutating"`. The `snapshots: {}` field is empty.
This PR resolves the issue above. The snapshots accumulated from the `group:` and `includeSnapshotsFrom:` keys are added to the mutatingConfig. This is also propagated to the `KubernetesMutating` binding and the binding-context.
```release-note
```
> fix: MutatingWebhook - Snapshots not being added

- pkg/config/config.go
- pkg/debug/server.go
- pkg/shell-operator/debug_server.go
- pkg/task/dump/dump.go
- pkg/task/dump/dump_test.go
Avoid double marshalling on json/yaml output when calling queue dump command - `queue list`
We have output formatter inside the router. So we have to avoid an extra marshalling when calling a queue dump
Before this change shell-operator had output with extra marshalling and printed a json like a string:
```
'{"active":[],"summary":{"mainQueueTasks":0,"otherQueues":{"active":0,"empty":72,"tasks":0},"totalTasks":0}}'
```
now it's ok:
```
{"active":[],"summary":{"mainQueueTasks":0,"otherQueues":{"active":0,"empty":72,"tasks":0},"totalTasks":0}}
```
> Fix queue dump output formatting

- pkg/app/debug.go
- pkg/debug/server.go
- pkg/shell-operator/debug_server.go
Deckhouse has an API that provides info on the state of its internal storage, queues, preflight patches, and more.
This API is now exposed via the Unix socket and can be accessed with the deckhouse-controller CLI.
Added an HTTP API server on localhost next to the socket server if "DebugHttpPort" is set.
We want to make it public and secure in deckhouse using kube-rbac-proxy.
> [deckhouse] Start HTTP API debug server if "DebugHttpPort" is set.

- pkg/app/debug.go
Deckhouse has an API that provides info on the state of its internal storage, queues, preflight patches, and more.
This API is now exposed via the Unix socket and can be accessed with the deckhouse-controller CLI.
Fix using debug flag "debug-http-addr".
During manual testing, the required flags were read in the "addon-operator". For this reason no error was detected.
> [deckhouse] Fix using debug flag "debug-http-addr".

- pkg/kube/object_patch/operation.go
- pkg/kube/object_patch/options.go
- pkg/kube/object_patch/patch.go
- pkg/kube/object_patch/patch_collector.go
- pkg/kube/object_patch/validation.go
- pkg/shell-operator/operator.go
This PR adds additional patch_option for Filter/Patch operations named `IgnoreHookError` and some execution logic around it.
If `IgnoreHookError` is set to true for a Filter/Patch operation and `WithSubresource` equals to `/status`, such an operation will be applied even in case of the hook failure.
It can come in handy in a situation when a hook operates around some kubernetes resource and one wants to make it more obvious when the resource was noticied/processed/etc by the hook last time by means of status fields.
This way we could provide some meaningful statuses or a feedback loop on what  happens when a hook is executed.
> add IgnoreHookError patch option

- pkg/hook/hook_manager.go
Handle shell hooks without config section
If executable hook doesn't have `config` section, shell-operator will panic. We need to handle this situation and throw an understandable error
> Handle empty config hook section

- pkg/utils/file/file.go
Ignore 100% non-executable hook files
With this files we can get some weird message about non-executable yaml file. I think we can absolutely ignore them.
`.yaml`, `.json`, `.md` and `.txt` could not be executable hooks anymore
> Ignore some file extensions

- pkg/hook/controller/kubernetes_bindings_controller.go
- pkg/shell-operator/bootstrap.go
- pkg/shell-operator/http_server.go
- pkg/shell-operator/metrics_hooks.go
- pkg/shell-operator/metrics_operator.go
- pkg/shell-operator/operator.go
- Separate `HookMetricStorage` and `MetricStorage`
- `MetricStorage` collects base go metrics and shell-opertor built-in metrics and returns on `/metrics`
- `HookMetricStorage` collects metrics from user hooks and returns on `/metrics/hooks`
- Increase HTTP Server timeouts
Separate base metrics from hook metrics
> Separate metric storages

- go.mod
- go.sum
- pkg/task/task.go
Fix race
We have a race here:
```
WARNING: DATA RACE
Read at 0x00c0064351e8 by goroutine 72:
github.com/flant/shell-operator/pkg/task.(*BaseTask).GetMetadata()
/go/pkg/mod/github.com/flant/shell-operator@v1.4.2/pkg/task/task.go:100 +0x37
github.com/flant/addon-operator/pkg/task.HookMetadataAccessor()
/go/pkg/mod/github.com/flant/addon-operator@v1.3.2/pkg/task/hook_metadata.go:48 +0x88
github.com/flant/addon-operator/pkg/addon-operator.taskDescriptionForTaskFlowLog()
/go/pkg/mod/github.com/flant/addon-operator@v1.3.2/pkg/addon-operator/operator.go:2040 +0x8a
github.com/flant/addon-operator/pkg/addon-operator.(*AddonOperator).logTaskAdd()
/go/pkg/mod/github.com/flant/addon-operator@v1.3.2/pkg/addon-operator/operator.go:2146 +0x197
github.com/flant/addon-operator/pkg/addon-operator.(*AddonOpe …
```
> Fix race condition

- pkg/app/webhook.go
- pkg/hook/config/config_v1.go
- pkg/shell-operator/bootstrap.go
- pkg/webhook/admission/manager.go
- pkg/webhook/admission/manager_test.go
- pkg/webhook/admission/resource.go
Add flag to set default FailurePolicy for ValidatingWebhookConfiguration
> Set default failure policy (config)

- examples/105-crd-simple/crd-simple.yaml
- examples/105-crd-simple/shell-operator-rbac.yaml
Update apiVersions in the crd-simple example
Kubernetes 1.27 uses updated API versions of the following kinds:
- CustomResourceDefinition
- ClusterRole
- ClusterRoleBinding
Also, CustomResourceDefinition v1 has the updated schema.
> Update apiVersions in the crd-simple example

- pkg/webhook/conversion/crd_client_config.go
- pkg/webhook/conversion/manager.go
The changes are described and tested in the context of [deckhouse PR](https://github.com/deckhouse/deckhouse/pull/7949)
Add repeated queries to get CRD and apply conversion strategies.
The occasion with the use of watch has been tried. It doesn't work. Because for a successful subscription - CRD must also already be installed in the cluster.
> Added retry budget and some refactoring.

- .github/workflows/lint.yaml
- docs/src/HOOKS.md
- pkg/hook/hook_manager.go
- pkg/utils/file/dir.go
- pkg/utils/file/file.go
- pkg/utils/file/file_test.go
- test/utils/directory.go
Hook spams like this:
```
.../hooks/lib/utils.py' is skipped: no executable permissions, chmod +x is required to run this hook"
```
Ignore lib directory while processing hooks. 
We also additionally check the files in the lib directory; if we find files with executable permissions, we display a warning.
Closes: #620
> feat: Ignore lib directory while processing hooks

- pkg/executor/executor.go
Updates the way executor collects executed commands' stderr.
This pr enriches executor's errors (if any) with stderr messages from executed commands (if any). It enables providing more meaningful errors from hooks/scripts than "command failed" to the end user.
> Catch stderr from executed commands

- docs/src/metrics/METRICS_FROM_HOOKS.md
- pkg/metric_storage/vault/collector.go
- pkg/metric_storage/vault/vault.go
- pkg/metric_storage/vault/vault_test.go
- pkg/utils/labels/labels.go
This pr update the way metrics with different label sets and the same name are stored in a collector.
If a new metric has a new label, this new label is added to the collector and all previous metrics in the collector get it with an empty string as its value.
Closes #616
> update merics' labelset if needed

- pkg/metric_storage/vault/collector.go
- pkg/metric_storage/vault/vault.go
- pkg/metric_storage/vault/vault_test.go
- pkg/utils/labels/labels.go
The pr updates the way new labelset are applied to metrics collectors. Also, a collector is updated only if a new metric's labelset isn't a subset of the collector's labelset (there is/are new label(s) on the metric).
When a metric is saved, it is checked that the metric's labels are a subset of the corresponding collector (if there is any) and if it isn't the case, the collector's labelset and stored metrics' labelsets are updated according to a new labelset (previous labels plus new labels from the metric about to store).
New labelsets for metrics collectors are sorted before applying.
> Improve the way of updating metrics collectors' labelsets

- pkg/app/webhook.go
We need to be able to configure the port and address on which the webhook will work
We add two new parameters at startup that are filled with default values. And you can change their value using environment variables.
Closed: #630
> feat: add setting for address and port for webhooks

- pkg/kube_events_manager/factory.go
- pkg/kube_events_manager/resource_informer.go
FactoryStore's get and Stop methods didn't save some modifications to the FactoryStore's map.
FactoryStore's get and Stop methods didn't save some modifications to the FactoryStore's map which would result in having inconsistent factory storage, leading to stopping resource informers prematurely.
> [kube_events_manager] fix informer factory

- pkg/kube_events_manager/factory.go
- pkg/kube_events_manager/resource_informer.go
This pr provides extra debug and fixes yet another bug in the shared factory store related to stopping all informers if the module, that triggered creation of the informers, has been disabled.
Currently, informers created for a module inherit the module monitor's context and if the module gets disabled, all the informers get disabled too. Given that we apply deduplication techniques to the factory store, disabling informers via the module's context isn't acceptable, so dedicated (per a shared informer factory) contexts were introduced.
Also, instead of using a counter for a factory to decide wether it can be safely stopped, a map of handler registrations was added. This map allows tracking of active resource informers and their handlers, and if a resource informer isn't needed any longer, …
> [kube-event-manager] fix factory context issue

- frameworks/shell/hook.sh
- pkg/hook/binding_context/binding_context.go
- pkg/hook/binding_context/binding_context_test.go
Fixes mapping of grouped binding contexts to `on_group` handlers in the shell-lib.
Adds additional `.groupName` field  to a binding context conversion result which is used to map grouped binding contexts to a `on_group` handler.
Updates shell-lib to use new `groupName` binding context field when mapping events to handlers.
> fix shell_lib regarding grouping

- pkg/schedule_manager/schedule_manager.go
Updates the `schedule-manager`'s Remove method to clean-up an entry from the `Entries` map if there are no associated schedule bindings left with the entry. 
It corrects the way schedule bindings of a module cleaned-up when the module is disabled. And, If the module is re-enabled, its schedule bindings are recreated correctly.
> [schedule-manager] fix entry clean-up

- pkg/executor/executor.go
Fixed logrus memory leak
Replace logrus Writer with bytes buffer
It fixes the logrus [memory leak](https://github.com/flant/shell-operator/issues/653)
> [shell-operator] Fix logrus leak

- pkg/metric/grouped_storage_mock.go
- pkg/metric/storage.go
- pkg/metric_storage/metric_storage.go
- pkg/metric_storage/vault/vault.go
- pkg/metric_storage/vault/vault_test.go
Provides `ExpireGroupMetricByName` method that is a slightly more efficient way of purging grouped metrics by their name.
Adds the aforementioned `ExpireGroupMetricByName` and provides `resolveMetricName` to a `GroupedVault` so that we could use GroupedVaults inside the addon-operator with metrics of `{PREFIX}_metric_name` format.
> [metric_storage] Metric storage group expire

- .golangci.yaml
- go.mod
- go.sum
- pkg/shell-operator/bootstrap.go
- pkg/shell-operator/kube_client.go
- test/integration/suite/run.go
> [shell-operator] bump kube client

- .golangci.yaml
- pkg/debug/server.go
- pkg/filter/jq/jq_exec.go
- pkg/hook/config/config_v0.go
- pkg/hook/config/config_v1.go
- pkg/hook/config/validator.go
- pkg/hook/config/versioned_untyped.go
- pkg/hook/hook.go
- pkg/hook/hook_manager.go
- pkg/hook/task_metadata/task_metadata.go
- pkg/kube/object_patch/helpers.go
- pkg/kube/object_patch/patch.go
- pkg/kube/object_patch/validation.go
- pkg/kube_events_manager/filter_test.go
- pkg/kube_events_manager/monitor.go
- pkg/kube_events_manager/monitor_config.go
- pkg/kube_events_manager/resource_informer.go
- pkg/shell-operator/bootstrap.go
- pkg/shell-operator/operator.go
- pkg/task/queue/task_queue.go
- pkg/task/queue/task_queue_test.go
- pkg/utils/file/dir.go
- pkg/webhook/admission/handler.go
- test/utils/directory.go
- test/utils/jsonloganalyzer.go
- test/utils/prometheus.go
- test/utils/shell-operator.go
> [ci] add nonamedreturns linter

- Makefile
- pkg/utils/file/file.go
- pkg/utils/file/file_test.go
Add errors to executable checking.
Handle errors with different log levels.
> [shell-operator] fix/add error and handling

- pkg/hook/controller/kubernetes_bindings_controller.go
- pkg/hook/controller/schedule_bindings_controller.go
- pkg/kube_events_manager/resource_informer.go
- pkg/task/dump/dump.go
- pkg/task/queue/task_queue.go
Some other race conditions to fix have been detected.
> Fix concurrent access #2

- pkg/utils/file/file.go
Adds an optional argument `excludedDirs` to `RecursiveGetExecutablePaths` helper function so that it would be possible to define extra exclusions when discovering executable files.
It's required for https://github.com/flant/addon-operator/pull/571.
> Add a list of excluded paths when discovering executable files

- pkg/hook/hook.go
- pkg/metric_storage/operation/operation.go
- pkg/metric_storage/operation/operation_test.go
- pkg/metric_storage/vault/vault.go
The previous behavior for hook execution had inconsistent metric handling that could lead to metric accumulation between hook runs.
When executing hooks, metrics were collected as-is without consistent grouping:
- ✅ If grouping was explicitly specified in the hook → metrics were grouped accordingly
- ❌ If no grouping was specified → metrics were saved without any grouping
- ⚠️ **Issue**: This behavior caused metrics to persist between hook executions, leading to potential data accumulation and inconsistency
The implementation now ensures consistent metric lifecycle management:
- 🔄 **All metrics without explicit grouping are automatically grouped by hook name**
- 📝 **Hook naming convention**: Derived from file path
- Example: `hooks/100-hook/some-hook.go` → Hook name: `100-hook/somehook`
- …
> [shell-operator] add default group to every hook

- pkg/hook/task_metadata/task_metadata.go
- pkg/hook/task_metadata/task_metadata_test.go
- pkg/shell-operator/combine_binding_context_test.go
- pkg/shell-operator/operator.go
- pkg/task/dump/dump_test.go
- pkg/task/queue/queue_set.go
- pkg/task/queue/task_queue.go
- pkg/task/queue/task_queue_benchmark_test.go
- pkg/task/queue/task_queue_compaction_test.go
- pkg/task/queue/task_queue_list.go
- pkg/task/queue/task_queue_requeue_test.go
- pkg/task/queue/task_queue_test.go
- pkg/task/task.go
- test/hook/context/context_combiner.go
This PR introduces a new linked list-based task queue implementation (`TaskQueue`) alongside the existing slice-based implementation (`TaskQueueSlice`). The new implementation provides consistent O(1) performance for all queue operations and includes a **new `compaction` function** that intelligently merges HookRun tasks for the same hook, significantly reducing queue size and improving processing efficiency.
**Problem Statement:**
The current slice-based queue implementation (`TaskQueueSlice`) suffers from catastrophic performance degradation for certain operations:
- `AddFirst`: O(n) complexity causing 160-200x slowdown compared to linked list
- `GetByID`: O(n) complexity with 6-53x performance degradation as queue size grows
- **Missing compaction functionality**: No mechanism to merge …
> [shell-operator] feat/compaction and queue refactor
