.circleci/config.yml
Dockerfile-alpine3.9

- build and push latest and latest-alpine tag2
- build and push on git tag

ci: initial circle ci config

---

pkg/kube_events_manager/kube_events_manager.go

Attempt to solve https://github.com/flant/shell-operator/issues/17

add autoscaling kind

---

HOOKS.md
pkg/executor/executor_test.go
pkg/hook/hook.go
pkg/hook/kube_event/hooks_controller.go
pkg/hook/kube_event/hooks_controller_test.go
pkg/kube/client.go
pkg/kube_events_manager/kube_events_manager.go
pkg/shell-operator/operator.go
pkg/task/task.go

Dynamic Informer

---

.circleci/config.yml
.dockerignore
Dockerfile
Dockerfile-alpine3.9
pkg/queue/queue.go

This PR allows you to actually use go modules.
Fix #34
Update: you are not using go modules in CI too :/
I've tried to update your CI configuration.

Fix go mod handling and data race

---

HOOKS.md
README.md
pkg/executor/executor.go
pkg/executor/executor_test.go
pkg/hook/hook.go
pkg/hook/hook_config.go
pkg/hook/hook_config_test.go
pkg/hook/hook_manager.go
pkg/hook/hook_test.go
pkg/hook/kube_event/hooks_controller.go
pkg/hook/kube_event/hooks_controller_test.go
pkg/hook/kube_event/kube_event_hook.go
pkg/hook/schedule/hooks_controller.go
pkg/hook/schedule/schedule_hook.go
pkg/kube_events_manager/kube_event.go
pkg/kube_events_manager/kube_event_informer.go
pkg/kube_events_manager/kube_events_manager.go
pkg/kube_events_manager/kube_monitor.go
pkg/kube_events_manager/util.go
pkg/queue/queue_test.go
pkg/schedule_manager/schedule.go
pkg/schedule_manager/schedule_manager_test.go
pkg/shell-operator/operator.go

Config versioning

---

HOOKS.md
pkg/hook/hook_config.go
pkg/hook/hook_config_test.go
pkg/kube/client.go
pkg/kube/client_test.go
pkg/kube_events_manager/kube_event_informer.go
pkg/kube_events_manager/kube_events_manager.go
pkg/kube_events_manager/kube_events_manager_test.go
pkg/kube_events_manager/kube_monitor.go
pkg/kube_events_manager/util.go
pkg/shell-operator/operator.go

Implement nameSelector support, fixes #33.

Name selector

---

pkg/hook/config/schemas.go
pkg/hook/hook_config_test.go

fix: watchEvent should be array

---

cmd/shell-operator/main.go
pkg/hook/config/schemas.go
pkg/hook/config/validator.go
pkg/hook/config/validator_test.go
pkg/hook/config/versioned_untyped.go
pkg/hook/hook_binding_context.go
pkg/hook/hook_binding_context_test.go
pkg/hook/hook_config.go
pkg/hook/kube_event/hooks_controller_test.go
pkg/hook/schedule/hooks_controller.go
pkg/hook/schedule/schedule_hook.go
pkg/kube_events_manager/kube_events_manager.go
pkg/kube_events_manager/kube_events_manager_test.go
pkg/shell-operator/operator.go

- refactor for addon-operator
- fix #56

fix: schedule hooks problems

---

pkg/kube_events_manager/resource_informer.go

`filterResult` field in binding context for Deleted event.

fix: filter result for deleted

---

examples/201-install-with-helm-chart/Chart.yaml
examples/201-install-with-helm-chart/README.md
examples/201-install-with-helm-chart/hooks/namespace-hook.sh
examples/201-install-with-helm-chart/templates/hook-configmap.yaml
examples/201-install-with-helm-chart/templates/shell-operator-deployment.yaml
examples/201-install-with-helm-chart/templates/shell-operator-rbac.yaml

This is a continuation of PR #24 with some changes for more simplicity.
Thank you @sekka1 for the original PR.

example: a helm chart verion of the 102-monitor-namespaces example

---

HOOKS.md
README.md
examples/200-advanced/shell-operator-deploy.yaml

Add documentation of environment variables

---

pkg/app/app.go
pkg/hook/binding_context/binding_context.go
pkg/hook/config/schemas.go
pkg/hook/config/validator_test.go
pkg/hook/config/versioned_untyped_test.go
pkg/hook/controller/hook_controller.go
pkg/hook/controller/schedule_bindings_controller.go
pkg/hook/hook.go
pkg/hook/hook_config.go
pkg/hook/hook_config_test.go
pkg/hook/types/bindings.go

- rename includeKubernetesSnapshots to includeSnapshots

fix: make temp files unique and clean them after hook execution

---

.circleci/config.yml
Dockerfile
Dockerfile-alpine3.10
cmd/shell-operator/main.go
go.mod
go.sum
pkg/app/app.go
pkg/app/debug.go
pkg/app/jq.go
pkg/app/log.go
pkg/app/start-cmd.go
pkg/debug/client.go
pkg/debug/debug-cmd.go
pkg/debug/server.go
pkg/kube/client_test.go
pkg/metrics_storage/metrics_storage.go
pkg/shell-operator/operator.go
test/hook/context/generator_test.go

Implementation of endpoint and cli commands for #8.

feat: debug endpoint and cli

---

go.mod
pkg/kube/client.go
pkg/kube/fake/cluster.go
pkg/kube/fake/resources.go
pkg/utils/manifest/manifest.go
pkg/utils/manifest/manifest_list.go
pkg/utils/manifest/manifest_list_test.go
pkg/utils/manifest/releaseutil/manifest.go
pkg/utils/manifest/releaseutil/manifest_test.go
test/hook/context/generator.go
test/hook/context/generator_test.go
test/hook/context/state.go
test/integration/suite/run.go

- create Manifest type to use in tests and in addon-operator helm functions

feat: excerpt a FakeCluster from hook testing framework

---

pkg/kube/fake/cluster.go
pkg/kube/fake/resources.go
test/hook/context/generator_test.go

Because of poor fake client GVR implementation, we need to add additional information for the GVR selection function.

tests: Add api version to GVR select function

---

pkg/kube/client.go
pkg/kube/client_test.go

- remove GroupVersionResourceByKind

feat: kubeclient: methods to get APIResource objects from cluster

---

pkg/kube_events_manager/resource_informer.go

Introduce a Mutex to concurently update and read ResourceMonitor's CachedObjects map.
```
fatal error: concurrent map iteration and map write
goroutine 44 [running]:
runtime.throw(0x1889ce1, 0x26)
/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0008068d8 sp=0xc0008068a8 pc=0x4391b2
runtime.mapiternext(0xc000806a08)
/usr/local/go/src/runtime/map.go:858 +0x579 fp=0xc000806960 sp=0xc0008068d8 pc=0x419159
github.com/flant/shell-operator/pkg/kube_events_manager.(*resourceInformer).GetExistedObjects(0xc000c44240, 0x0, 0x0, 0x27b6008)
...
goroutine 1322 [runnable]:
github.com/flant/libjq-go/pkg/jq.CgoCall(0xc0009c5e00)
/go/pkg/mod/github.com/flant/libjq-go@v1.0.1-0.20200205115921-27e93c18c17f/pkg/jq/cgo_caller.go:33 +0xdc
github.com/flant/libjq-go/pkg/jq.(*JqProgram).Run(0xc000bffdc0, …
```

fix: lock for GetExistingObjects

---

HOOKS.md
README.md
examples/101-monitor-pods/hooks/pods-hook.sh
examples/102-monitor-namespaces/hooks/namespace-hook.sh
examples/104-secret-copier/hooks/add_or_update_secret
examples/104-secret-copier/hooks/create_namespace
examples/104-secret-copier/hooks/delete_secret
examples/105-crd-simple/hooks/crd-hook.sh
examples/200-advanced/hooks/namespace-hook.sh
examples/201-install-with-helm-chart/hooks/namespace-hook.sh
pkg/hook/config/schemas.go
pkg/hook/hook_config.go
pkg/hook/hook_config_test.go
pkg/kube_events_manager/monitor_config.go
pkg/kube_events_manager/resource_informer.go

- if binding has empty `executeHookOnEvent`, then hook is never
executed, this binding is for snapshots only.

feat: watchEvent is an alias of executeHookOnEvent, support empty array

---

HOOKS.md
pkg/hook/binding_context/binding_context.go
pkg/hook/binding_context/binding_context_test.go
pkg/hook/hook_manager.go
pkg/hook/task_metadata/task_metadata.go
pkg/shell-operator/operator.go

- fix Synchronization for groups
- fix start of schedule bindings

docs: group key

---

pkg/hook/task_metadata/task_metadata.go
pkg/kube_events_manager/namespace_informer.go
pkg/kube_events_manager/resource_informer.go
pkg/shell-operator/operator.go
pkg/shell-operator/operator_test.go
pkg/task/queue/task_queue.go

- fix: kube_event_manager: support for DeletedFinalStateUnknown

fix: make CombineBingingContextForHook usable by addon-operator

---

examples/002-startup-python/Dockerfile
examples/105-crd-simple/Dockerfile
examples/106-monitor-events/Dockerfile
examples/200-advanced/Dockerfile
examples/200-advanced/README.md

- update image version alpine3.9 to alpine 3.11
fixes #154

fix: use alpine for example with python

---

frameworks/shell/hook.sh

The new type of event added to the shell framework.

[shell framework] hook handler with Groups

---

pkg/app/kube-client.go
pkg/kube/client.go

- analog of kubectl --server flag

feat: server option for kubernetes client

---

go.mod
go.sum

fix: update libjq-go to v1.6.1

---

METRICS.md
pkg/shell-operator/operator.go

- reset queuedAt for failed HookRun task for correct results in task_wait_in_queue
- update metric descriptions

fix: snapshot_size description, fix wait_in_queue

---

examples/102-monitor-namespaces/hooks/namespace-hook.sh

Fix for bash handler script in order to iterate through BINDING_CONTEXT_PATH array

issue-192: iterate through events array in namespace example

---

shell_lib.sh

Perhaps, there could be a better place for this, alas, its location is already a part of the KubeCon 2020 video.

Add a sourceable shell_lib.sh

---

pkg/kube_events_manager/monitor_config.go
pkg/kube_events_manager/resource_informer.go
pkg/kube_events_manager/util.go
test/hook/context/generator.go
test/hook/context/generator_test.go

- add full BindingContext in testing/generator

feat: addon-operator can override jq filter function

---

.github/workflows/release-build.yaml
Dockerfile-alpine3.12

Created this PR because alpine 3.12 has been out for a while and it seems missing from this project.
P.S. Thank you for creating this, I had a blast watching the KubeCon talk a few weeks ago and working on an operator today :+1:

Add Alpine 3.12

---

Dockerfile
METRICS.md
pkg/metric_storage/metric_storage.go
pkg/metric_storage/operation/operation.go
pkg/metric_storage/operation/operation_test.go
pkg/metric_storage/vault/collector.go
pkg/metric_storage/vault/vault.go
pkg/metric_storage/vault/vault_test.go

- fix: expire all metrics in group before apply new state

feat: expire action to explicitly expire all metrics in group

---

pkg/utils/file/file.go

This PR is aimed to improve the UX part. Without logs, it is confusing that hooks were skipped for some reason.

feat: Warn users about non-executable hooks

---

pkg/kube_events_manager/namespace_informer.go
pkg/kube_events_manager/resource_informer.go
pkg/kube_events_manager/util.go
pkg/kube_events_manager/util_test.go

fix: randomize resync period to eliminate cpu peaks

---

METRICS.md
pkg/executor/executor.go
pkg/hook/hook.go
pkg/kube_events_manager/resource_informer.go
pkg/shell-operator/metrics.go
pkg/shell-operator/operator.go

- cpu sys and user milliseconds
- max rss kilobytes

feat: metrics with hook resource usage

---

pkg/task/queue/task_queue.go

Use RWMutex in the TaskQueue, use read locks for read-only operations.
```release-note
NONE
```

feat: read only locks for queue read operations

---

.github/workflows/publish-dev-amd64.yaml
.github/workflows/publish-release.yaml

Push flant/shell-operator:latest on release.
There is a separate workflow to update a latest tag, but build supports pushing multiple tags.
No
```release-note
```

feat(ci): update latest tag on release

---

examples/204-validating-webhook/README.md

Fixes broken link.
Current link is 404.
No.

link to binding validating

---

examples/002-startup-python/Dockerfile
examples/105-crd-simple/Dockerfile
examples/106-monitor-events/Dockerfile

Valid docker tag in exmaples.
Current tag is not present in docker hub.
No.

tag latest-alpine3.11 not present in docker hub

---

.github/workflows/lint.yaml
test/utils/jsonloganalyzer.go
test/utils/jsonlogrecord.go
test/utils/kind-k8s-cluster.go
test/utils/prometheus.go
test/utils/shell-operator.go

Fix golint issues
```release-note
```

fix(ci): add build tags for golint, fix linter issues

---

HOOKS.md
pkg/hook/hook.go
test/integration/kubeclient/object_patch_test.go

- parallel integration tests for object patcher
- remove tmp file for conversion response
- executionMinInterval in HOOKS.md
```release-note
```

fix: some issues from recent PRs

---

RUNNING.md
pkg/app/kube-client.go
pkg/kube/client.go
pkg/shell-operator/operator.go

Set global request timeout for Kubernetes client
Some operations (especially in the "object_patch" package) may get stuck for an inordinate amount of time.
```release-note
```

Set global request timeout for Kubernetes client

---

cmd/shell-operator/main.go
pkg/app/debug.go
pkg/utils/klogtologrus/adapter.go
pkg/utils/klogtologrus/test/adapter_test.go

* Add ability to filter klog wrapped messages
* Enable klog wrapper after parsing flags
* Provide flag and env variable to enable Kubernetes API debugging messages
This PR adds features to make working with wrapped logs more efficient and convenient.
```release-note
Add flag and env variable to enable Kubernetes API debugging messages
```

feat: improve klog wrapper

---

.github/ISSUE_TEMPLATE/config.yml

Ask questions on the Github Discussions instead of Flant community site
We decided to switch to discussions because it already has all the necessary features
```release-note
```

fix: change forum link

---

pkg/hook/config/config_test.go
test/hook/context/generator.go
test/hook/context/generator_test.go

Fix generator.go to skip BindingContext for binding with "executeHookOnSynchronization: false"
```release-note
```

fix(generator): do not return BindingContext if Synchronization is skipped

---

pkg/hook/binding_context/binding_context_test.go
pkg/kube_events_manager/filter.go
pkg/kube_events_manager/monitor_config.go
pkg/kube_events_manager/types/types.go
test/hook/context/generator.go

We want typed filter results for Go hooks.
Related PR in addon-operator: https://github.com/flant/addon-operator/pull/180
There are no changes in shell hooks configuration.
```release-note
```

Send empty interface{} to the filterFunc

---

.github/workflows/code-checks.yaml
go.mod
go.sum
test/hook/context/context_combiner.go
test/hook/context/generator.go
test/hook/context/generator_test.go

- Add "AllSnapshots" binding context generator.
- Replace custom binding context combiner for tests with CombineBindingContextForHook from ShellOperator.
```release-note
```

feat(tests): add "AllSnapshots" binding context generator

---

test/hook/context/context_combiner.go

Replace "main" with the constant.
Fix panic in tests.
```release-note
```

fix(test): replace hardcode in ContextCombiner

---

pkg/kube/object_patch/patch.go
pkg/kube/object_patch/types.go
pkg/kube/object_patch/validation.go

Closes https://github.com/flant/shell-operator/issues/278
```release-note
Implemented CreateIfNotExists in the object patcher
```

Implemented CreateIfNotExists in the object patcher

---

pkg/hook/controller/hook_controller.go
pkg/hook/controller/kubernetes_bindings_controller.go
pkg/kube_events_manager/monitor.go

Implement UpdateMonitor method to change kind and apiVersion of an existing monitor.
This PR is a base for PR in addon-operator https://github.com/flant/addon-operator/pull/216
```release-note
```

feat: add and remove kubernetes bindings in hook controller

---

HOOKS.md

Correctly reference the right snapshot name, _I think_
I was reading through the docs and this didn't make sense to me so I've made a change to what I expect it to be. If my change is in error could you explain what the "cm" is in reference to? Thanks.
```
Fix snapshot reference in HOOKS doc
```

Fix snapshot reference in HOOKS doc

---

.github/workflows/publish-dev.yaml
Dockerfile

arm64 image contains kubectl for amd64. See #311.
Add ARG TARGETPLATFORM after FROM.
```release-note
```

fix ARG TARGETPLATFORM not available in RUN

---

BINDING_CONVERSION.md

Small doc fix
```release-note
NONE
```

chore: add a note about openapi specs and conversion webhooks

---

.github/workflows/publish-dev-amd64.yaml
.github/workflows/publish-dev.yaml
.github/workflows/tests.yaml
pkg/kube/object_patch/patch_collector.go

github-script v5 use updated octokit, so replace `github.issues` -> `github.rest.issues`
```release-note
```

fix(ci): update github-script to v5

---

go.mod
pkg/kube/object_patch/patch.go
pkg/kube/object_patch/patch_test.go

Add more info to errors
Otherwise, it is impossible to know which operation is failing
```release-note
```

Add more info about failed patcher operations

---

cmd/shell-operator/main.go
pkg/debug/debug-cmd.go
pkg/debug/server.go
pkg/hook/binding_context/binding_context_test.go
pkg/hook/controller/hook_controller.go
pkg/hook/controller/kubernetes_bindings_controller.go
pkg/kube_events_manager/monitor.go
pkg/kube_events_manager/resource_informer.go
pkg/kube_events_manager/types/types.go
pkg/kube_events_manager/types/types_test.go
pkg/kube_events_manager/util.go
pkg/shell-operator/operator.go
pkg/task/dump/dump.go

- debug command to get hook list
- debug command to get hook snapshots
- print snapshots info in log on every hook run
Make hooks debugging a little easy.
```release-note
```

feat(debug): command to get snapshots

---

pkg/kube_events_manager/kube_events_manager.go
pkg/kube_events_manager/monitor.go
pkg/kube_events_manager/namespace_informer.go
pkg/kube_events_manager/resource_informer.go
test/hook/context/README.md
test/hook/context/generator.go
test/hook/context/generator_test.go
test/hook/context/state.go

fix(testing): speedup binding context generator

---

.golangci.yaml
pkg/hook/hook.go
pkg/kube/object_patch/patch_test.go
pkg/metric_storage/operation/operation.go
pkg/utils/checksum/checksum.go
pkg/webhook/conversion/handler.go
pkg/webhook/conversion/manager.go
pkg/webhook/conversion/response.go
pkg/webhook/server/server.go
pkg/webhook/server/server_test.go
pkg/webhook/validating/handler.go
pkg/webhook/validating/manager.go
pkg/webhook/validating/types/response.go

- remove excluded static checks
- add more linters

chore: replace deprecated ioutil methods

---

examples/206-mutating-webhook/.dockerignore
examples/206-mutating-webhook/.helmignore
examples/206-mutating-webhook/Chart.yaml
examples/206-mutating-webhook/Dockerfile
examples/206-mutating-webhook/README.md
examples/206-mutating-webhook/crontab-valid.yaml
examples/206-mutating-webhook/gen-certs.sh
examples/206-mutating-webhook/hooks/mutating.sh
examples/206-mutating-webhook/templates/certs-secret.yaml
examples/206-mutating-webhook/templates/crd/crontab.yaml
examples/206-mutating-webhook/templates/deployment.yaml
examples/206-mutating-webhook/templates/rbac.yaml
examples/206-mutating-webhook/templates/webhook-service.yaml
examples/206-mutating-webhook/values.yaml

Example for mutating webhook. See #439

docs: example for mutating webhook

---

frameworks/shell/hook.sh
pkg/hook/binding_context/binding_context.go
pkg/hook/controller/admission_bindings_controller.go
pkg/hook/hook.go
pkg/hook/hook_manager.go
pkg/hook/hook_manager_test.go
pkg/shell-operator/bootstrap.go
pkg/shell-operator/operator.go
pkg/webhook/admission/handler.go
pkg/webhook/admission/manager.go
pkg/webhook/admission/types/event.go
pkg/webhook/admission/types/response.go

- replace deprecated ioutil methods
- rename validating to admission
- fix empty "binding" label for mutating/validating
- add "type": "Mutating" in binding context
- add mutating handler in shell framework
```release-note
```

chore: some cleanups

---

RUNNING.md
pkg/app/app.go

chore: bump version strings to 1.2.0

---

.github/workflows/publish-dev.yaml
.github/workflows/publish-release.yaml

fix(ci): ignore unknown platform in inspect, push dev image to ghcr only

---

README.md
examples/220-execution-rate/README.md

HOOKS.md was moved in e5da08d19823c872af8b4aad6448c7073d48c117. Some links was forgotten.
Links are broken now.

links to HOOKS.md after move in e5da08d19823c872af8b4aad6448c7073d48c117

---

examples/230-configmap-python/Dockerfile
examples/230-configmap-python/README.md
examples/230-configmap-python/hooks/00-hook.py
examples/230-configmap-python/shell-operator-pod.yaml

Add example with python client library
Example with python kubernetes client library with in-cluster config

Add example with python client library

---

pkg/debug/debug-cmd.go
pkg/shell-operator/debug_server.go
pkg/task/dump/dump.go
pkg/task/dump/dump_test.go

Add format(text, json, yaml) for the `queue list` command
Empty queues are hide by default, you can add flag `--show-empty` to print them
Output formatting were broken before.
Empty queues generated a lot of useless output.
`text` format left as is.
`json` format looks like: 
```json
{
"active": [
{
"name": "main",
"tasksCount": 5,
"tasks": [
{
"index": 1,
"description": ":::test_task_main_0004"
},
{
"index": 2,
"description": ":::test_task_main_0003"
},
{
"index": 3,
"description": ":::test_task_main_0002"
},
{
"index": 4,
"description": ":::test_task_main_0001"
},
{
"index": 5,
"description": ":::test_task_main_0000"
}
]
},
{
"name": "active-queue",
"tasksCount": 4,
"tasks": [
{
"index": 1,
"description": ":::test_task_active-queue_0003"
},
{
"index": 2,
"description": …
```

[feature] Add format for `queue list` command

---

docs/src/BINDING_CONVERSION.md
docs/src/BINDING_VALIDATING.md
docs/src/HOOKS.md
docs/src/KUBERNETES.md
docs/src/QUICK_START.md
docs/src/README.md
docs/src/RUNNING.md
docs/src/metrics/METRICS_FROM_HOOKS.md
examples/104-secret-copier/README.md
pkg/kube_events_manager/kube_events_manager_test.go
pkg/kube_events_manager/resource_informer.go

- external links to dedicated list
- apply fixes to links
This PR fixes links in auto-generated doc.
--

Fix links in docs

---

pkg/app/webhook.go
pkg/shell-operator/bootstrap.go
pkg/webhook/admission/manager.go
pkg/webhook/admission/manager_test.go
pkg/webhook/admission/settings.go

Add flag to set default FailurePolicy for ValidatingWebhookConfiguration

Set Default FailurePolicy for admission webhooks

---

pkg/webhook/conversion/crd_client_config.go

Added repeated crd requests.
related to https://github.com/deckhouse/deckhouse/pull/7827

Fix taking a crd that is not yet installed

---

test/hook/context/generator.go
test/hook/context/state.go

Increase timeout for  binding contexts generator in tests.
It fixes flaky tests.

Increase timeout for binding contexts generator in tests.

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/tests-labeled.yaml
.github/workflows/tests.yaml
Dockerfile

Use golang 1.22
Kubectl binary was changed to the 1.27 version

Use golang 1.22

---

pkg/utils/file/file.go

Optimize executable hook files detection

---

docs/src/HOOKS.md
pkg/hook/binding_context/binding_context.go
pkg/hook/binding_context/binding_context_test.go

`binding` field of a grouped binding doesn't get updated to the group name.
Preserving original binding name in a grouped binding context makes debugging hooks` events more straightforward.

update grouped binding naming

---

pkg/task/task.go

This method is required to sync combined tasks' status.

add GetFailureMessage method

---

pkg/hook/task_metadata/task_metadata.go
pkg/shell-operator/operator.go
pkg/task/task.go

Refactor task and task-metadata

---

pkg/task/queue/task_queue.go

Fixes the queue retry delay counter message so that it correctly posts how many seconds left till next retry.

[queue] fix retry message

---

pkg/executor/executor.go
pkg/executor/executor_test.go

Chrooted executor

---

pkg/shell-operator/manager_events_handler.go
pkg/task/queue/queue_set.go

Fixes sporadic concurrent map read/write access.
Based on debugging with `-race`.

Fix concurrent map access in task queues

---

pkg/kube/object_patch/operation.go
pkg/kube/object_patch/options.go
pkg/kube/object_patch/patch_test.go

Change Options names

---

go.mod
go.sum
pkg/debug/debug-cmd.go

Adds two more flags to the "queue list" to keep refreshing "queue list" output on a defined interval.
```
-w, --watch               Keep watching.
-t, --watchInterval="1s"  Watch refresh interval.
```

[debug] add watch to queue list

---

.github/workflows/lint.yaml
.golangci.yaml
pkg/config/config.go
pkg/debug/debug-cmd.go

Update golangci-lint version
This pull request includes updates to the Go project's linting configuration, optimizations to string handling for improved performance, and a significant refactor to simplify webhook metadata handling. Below is a breakdown of the most important changes:
* Updated `golangci-lint` to version `v2.1.6` in the GitHub Actions workflow and removed the `--sort-results` flag. (`.github/workflows/lint.yaml`)
* Refactored `.golangci.yaml`:
- Removed the `run.timeout` setting and restructured the configuration to use `version: "2"`.
- Disabled several linters (`gci`, `gofmt`, `gofumpt`, etc.) and added `copyloopvar` to the enabled list.
- Introduced new `settings` and `exclusions` sections for better control over linter behavior. …

feat: update golangci-lint

---

.golangci.yaml
pkg/debug/debug-cmd.go
pkg/hook/config/config_v1.go
pkg/kube_events_manager/namespace_informer.go
pkg/kube_events_manager/types/types_test.go
pkg/shell-operator/combine_binding_context.go
pkg/shell-operator/combine_binding_context_test.go
pkg/shell-operator/operator.go
pkg/utils/file/file_test.go
test/hook/context/generator_test.go

Add linters
- errcheck
- musttag
- unparam
- usestdlibvars

[shell-operator] add linters and lint

---

cmd/shell-operator/main.go
go.mod
go.sum
pkg/executor/executor.go
pkg/executor/executor_test.go
pkg/metric_storage/vault/vault_test.go
pkg/shell-operator/operator.go
pkg/utils/file/file_test.go
pkg/utils/structured-logger/structured_logger.go
pkg/webhook/admission/handler.go
pkg/webhook/conversion/handler.go

Bump deckhouse logger (add options pattern)
Bump go-client (fixed dependencies, fixed klog logs pattern)

[shell-operator] Bump deckhouse logger 

---

internal/metrics/metrics.go
pkg/debug/debug-cmd.go
pkg/shell-operator/combine_binding_context_test.go
pkg/shell-operator/metrics_operator.go
pkg/shell-operator/operator.go
pkg/shell-operator/operator_test.go
pkg/task/dump/dump_test.go
pkg/task/queue/queue_set.go
pkg/task/queue/task_counter.go
pkg/task/queue/task_queue.go
pkg/task/queue/task_queue_benchmark_test.go
pkg/task/queue/task_queue_compaction_test.go
pkg/task/queue/task_queue_list.go
pkg/task/queue/task_queue_requeue_test.go
pkg/task/queue/task_queue_test.go
pkg/task/task.go
pkg/utils/list/list.go
pkg/utils/list/list_test.go

Start compaction only for 100+ counted tasks.
Add metrics for compaction tasks.
Add generic linked list

[shell-operator] Count tasks to start compaction

---

go.mod
go.sum

[shell-operator] bump module-sdk

---

pkg/task/queue/task_queue_list.go

[shell-operator] fix: queue micro deadlock fix
